SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS task_label;
DROP TABLE IF EXISTS label;
DROP TABLE IF EXISTS task_category;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS collaboration;
DROP TABLE IF EXISTS recurring_task;
DROP TABLE IF EXISTS task_dependency;
DROP TABLE IF EXISTS attachment;
DROP TABLE IF EXISTS reminder;
DROP TABLE IF EXISTS checklist;
DROP TABLE IF EXISTS subtasks;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;